# Generated by Django 6.0.4 on 2026-05-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todoitem_todolist_delete_todo_todoitem_todo_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
